services:
  mongo-db:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
    ports:
      - '${DATABASE_PORT}:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
